[workspace]
members = [
    "crates/airpods-app-core",
    "crates/airpods-aap-core",
    "crates/airpods-aap-py",
    "crates/airpods-client",
    "crates/airpods-client-c",
    "crates/airpods-client-resilient",
    "crates/airpodsctl",
    "crates/airpods-hub-core",
    "crates/airpods-sdp-core",
]
resolver = "3"
