"""Version 0.1 asyncio client for the local airpods-hubd service."""

from airpods_client.client import (
    AirPodsClient,
    AirPodsClientError,
    ConnectionClosed,
    ConnectionFailed,
    DaemonError,
    DaemonState,
    EventBufferFull,
    FrameTooLarge,
    HeartRateSample,
    HeartRateSubscription,
    Hello,
    InvalidMessage,
    ProtocolVersionError,
    SourceSide,
    Status,
    SubscriptionActive,
    XdgRuntimeDirMissing,
)

__all__ = [
    "AirPodsClient",
    "AirPodsClientError",
    "ConnectionClosed",
    "ConnectionFailed",
    "DaemonError",
    "DaemonState",
    "EventBufferFull",
    "FrameTooLarge",
    "HeartRateSample",
    "HeartRateSubscription",
    "Hello",
    "InvalidMessage",
    "ProtocolVersionError",
    "SourceSide",
    "Status",
    "SubscriptionActive",
    "XdgRuntimeDirMissing",
]
