"""Install the production daemon as a relocatable systemd user service."""

from __future__ import annotations


import os

import sys

from collections.abc import Mapping
from dataclasses import dataclass
from pathlib import Path


UNIT_NAME = "airpods-hubd.service"
OWNERSHIP_MARKER = "# X-AirPods-HR-Linux-Managed: 1"
SYSTEMCTL_TIMEOUT = 15.0


class ServiceInstallerError(RuntimeError):
    """Base error for safe service installation failures."""


@dataclass(frozen=True)
class InstallationState:
    unit_path: Path
    exists: bool
    owned: bool
    exec_start_matches: bool
    expected_exec_start: str
    installed_exec_start: str | None

    @property
    def valid(self) -> bool:
        return self.exists and self.owned and self.exec_start_matches


def user_unit_path(environment: Mapping[str, str] | None = None) -> Path:
    """Resolve the systemd user unit path using the XDG config convention."""

    env = os.environ if environment is None else environment
    xdg_config_home = env.get("XDG_CONFIG_HOME")
    if xdg_config_home:
        base = Path(xdg_config_home).expanduser()
    else:
        home = env.get("HOME")
        if not home:
            raise ServiceInstallerError(
                "HOME is required when XDG_CONFIG_HOME is unset"
            )
        base = Path(home).expanduser() / ".config"
    if not base.is_absolute():
        raise ServiceInstallerError("user configuration directory must be absolute")
    return base / "systemd" / "user" / UNIT_NAME


def installed_python(executable: str | os.PathLike[str] | None = None) -> Path:
    """Return the absolute interpreter path without resolving a venv symlink."""

    raw = os.fspath(executable) if executable is not None else sys.executable
    if not raw:
        raise ServiceInstallerError("current Python executable is unavailable")
    path = Path(os.path.abspath(raw))
    if not path.is_absolute():
        raise ServiceInstallerError("current Python executable must be absolute")
    if executable is None and not path.is_file():
        raise ServiceInstallerError(f"current Python executable does not exist: {path}")
    return path


def systemd_quote_argument(value: str) -> str:
    """Quote one systemd command argument without applying shell semantics."""

    if not value:
        raise ServiceInstallerError("systemd command argument must not be empty")
    if any(ord(character) < 32 or ord(character) == 127 for character in value):
        raise ServiceInstallerError(
            "systemd command argument contains a control character"
        )
    escaped = (
        value.replace("\\", "\\\\")
        .replace('"', '\\"')
        .replace("$", "$$")
        .replace("%", "%%")
    )
    return f'"{escaped}"'


def exec_start_for(python: Path) -> str:
    if not python.is_absolute():
        raise ServiceInstallerError("daemon Python executable must be absolute")
    return f"{systemd_quote_argument(os.fspath(python))} -m airpods_hr._hubd.main"


def render_unit(python: Path) -> str:
    """Render the sole authoritative production user-unit definition."""

    exec_start = exec_start_for(python)
    return f"""{OWNERSHIP_MARKER}
# Generated by airpods-hubd-service. Local edits may be replaced.
[Unit]
Description=AirPods persistent local sensor daemon

[Service]
Type=simple
ExecStart={exec_start}
Restart=no
KillSignal=SIGTERM
SuccessExitStatus=130 143
TimeoutStopSec=330
UMask=0077
NoNewPrivileges=yes

[Install]
WantedBy=default.target
"""


def is_project_owned(contents: str) -> bool:
    return contents.startswith(f"{OWNERSHIP_MARKER}\n")


def _path_exists(path: Path) -> bool:
    return os.path.lexists(path)


def _installed_exec_start(contents: str) -> str | None:
    values = [
        line.removeprefix("ExecStart=")
        for line in contents.splitlines()
        if line.startswith("ExecStart=")
    ]
    if len(values) != 1:
        return None
    return values[0]


def inspect_installation(unit_path: Path, python: Path) -> InstallationState:
    expected = exec_start_for(python)
    if not _path_exists(unit_path):
        return InstallationState(unit_path, False, False, False, expected, None)
    try:
        contents = unit_path.read_text(encoding="utf-8")
    except OSError as error:
        raise ServiceInstallerError(
            f"cannot read service unit {unit_path}: {error}"
        ) from error
    installed = _installed_exec_start(contents)
    return InstallationState(
        unit_path,
        True,
        is_project_owned(contents),
        installed == expected,
        expected,
        installed,
    )


