//! Deterministic systemd user-service policy. Python owns every file and subprocess effect.

pub const UNIT_NAME: &str = "airpods-hubd.service";
pub const OWNERSHIP_MARKER: &str = "# X-AirPods-HR-Linux-Managed: 1";

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum Operation {
    DaemonReload,
    Enable,
    Disable,
}

impl Operation {
    pub fn parse(value: &str) -> Option<Self> {
        match value {
            "daemon-reload" => Some(Self::DaemonReload),
            "enable" => Some(Self::Enable),
            "disable" => Some(Self::Disable),
            _ => None,
        }
    }
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::DaemonReload => "daemon-reload",
            Self::Enable => "enable",
            Self::Disable => "disable",
        }
    }
}

pub fn systemctl_argv(executable: &str, operation: Operation) -> Vec<String> {
    let mut argv = vec![
        executable.to_owned(),
        "--user".into(),
        "--no-ask-password".into(),
        operation.as_str().into(),
    ];
    if operation != Operation::DaemonReload {
        argv.push(UNIT_NAME.into());
    }
    argv
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum ExecutableError {
    NotAbsolute,
    ControlCharacter,
    DoubleQuote,
    SingleQuote,
    Backslash,
    DollarSign,
    Asterisk,
    QuestionMark,
    OpeningSquareBracket,
}

impl ExecutableError {
    pub const fn message(self) -> &'static str {
        match self {
            Self::NotAbsolute => "daemon Python executable must be absolute",
            Self::ControlCharacter => "daemon Python executable contains a control character",
            Self::DoubleQuote => "daemon Python executable contains unsupported double quote",
            Self::SingleQuote => "daemon Python executable contains unsupported single quote",
            Self::Backslash => "daemon Python executable contains unsupported backslash",
            Self::DollarSign => "daemon Python executable contains unsupported dollar sign",
            Self::Asterisk => "daemon Python executable contains unsupported asterisk",
            Self::QuestionMark => "daemon Python executable contains unsupported question mark",
            Self::OpeningSquareBracket => {
                "daemon Python executable contains unsupported opening square bracket"
            }
        }
    }

    pub fn format_message(self, path: &str) -> String {
        match self {
            Self::NotAbsolute | Self::ControlCharacter => self.message().to_owned(),
            Self::DoubleQuote
            | Self::SingleQuote
            | Self::Backslash
            | Self::DollarSign
            | Self::Asterisk
            | Self::QuestionMark
            | Self::OpeningSquareBracket => format!("{}: {path}", self.message()),
        }
    }
}

pub fn render_executable(path: &str) -> Result<String, ExecutableError> {
    if !path.starts_with('/') {
        return Err(ExecutableError::NotAbsolute);
    }
    if path.chars().any(|c| c < ' ' || c == '\u{7f}') {
        return Err(ExecutableError::ControlCharacter);
    }
    for (character, error) in [
        ('"', ExecutableError::DoubleQuote),
        ('\'', ExecutableError::SingleQuote),
        ('\\', ExecutableError::Backslash),
        ('$', ExecutableError::DollarSign),
        ('*', ExecutableError::Asterisk),
        ('?', ExecutableError::QuestionMark),
        ('[', ExecutableError::OpeningSquareBracket),
    ] {
        if path.contains(character) {
            return Err(error);
        }
    }
    Ok(format!("\"{}\"", path.replace('%', "%%")))
}

pub fn exec_start(path: &str) -> Result<String, ExecutableError> {
    Ok(format!(
        "{} -m airpods_hr._hubd.main",
        render_executable(path)?
    ))
}

pub fn render_unit(path: &str) -> Result<String, ExecutableError> {
    Ok(unit_definition(&exec_start(path)?, "NoNewPrivileges=yes"))
}

fn unit_definition(command: &str, privileges: &str) -> String {
    format!(
        "{OWNERSHIP_MARKER}\n# Generated by airpods-hubd-service. Local edits may be replaced.\n[Unit]\nDescription=AirPods persistent local sensor daemon\n\n[Service]\nType=simple\nExecStart={command}\nRestart=no\nKillSignal=SIGTERM\nSuccessExitStatus=130 143\nTimeoutStopSec=330\nUMask=0077\n{privileges}\n\n[Install]\nWantedBy=default.target\n"
    )
}

/// Fixed packaged command; shares the same fail-closed executable policy.
pub fn appimage_exec_start(path: &str) -> Result<String, ExecutableError> {
    Ok(format!(
        "{} --internal-daemon-service",
        render_executable(path)?
    ))
}

/// FUSE must mount before privilege escalation is disabled. AppRun sets
/// no_new_privs immediately before execing the bundled daemon interpreter.
/// Keep FUSE alive during Python's SIGTERM cleanup by signalling the main PID.
pub fn render_appimage_unit(path: &str) -> Result<String, ExecutableError> {
    Ok(unit_definition(
        &appimage_exec_start(path)?,
        "NoNewPrivileges=no\nKillMode=mixed",
    ))
}

pub fn is_project_owned(contents: &str) -> bool {
    contents.starts_with(&format!("{OWNERSHIP_MARKER}\n"))
}

pub fn installed_exec_start(contents: &str) -> Option<&str> {
    let mut values = contents
        .split([
            '\n', '\r', '\u{b}', '\u{c}', '\u{1c}', '\u{1d}', '\u{1e}', '\u{85}', '\u{2028}',
            '\u{2029}',
        ])
        .filter_map(|line| line.strip_prefix("ExecStart="));
    let first = values.next()?;
    values.next().is_none().then_some(first)
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct InstallationState {
    pub owned: bool,
    pub exec_start_matches: bool,
    pub installed_exec_start: Option<String>,
}

pub fn installation_state(contents: Option<&str>, expected_exec_start: &str) -> InstallationState {
    let Some(contents) = contents else {
        return InstallationState {
            owned: false,
            exec_start_matches: false,
            installed_exec_start: None,
        };
    };
    let installed = installed_exec_start(contents);
    InstallationState {
        owned: is_project_owned(contents),
        exec_start_matches: installed == Some(expected_exec_start),
        installed_exec_start: installed.map(str::to_owned),
    }
}

pub const fn installation_valid(exists: bool, owned: bool, exec_start_matches: bool) -> bool {
    exists && owned && exec_start_matches
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum Action {
    WriteUnit,
    UnlinkUnit,
    DaemonReload,
    Enable,
    Disable,
}

pub fn install_plan(
    exists: bool,
    owned: bool,
    force: bool,
    enable: bool,
) -> Result<Vec<Action>, &'static str> {
    if exists && !owned && !force {
        return Err("foreign unit");
    }
    let mut actions = vec![Action::WriteUnit, Action::DaemonReload];
    if enable {
        actions.push(Action::Enable);
    }
    Ok(actions)
}

pub fn uninstall_plan(
    exists: bool,
    owned: bool,
    disable: bool,
) -> Result<Vec<Action>, &'static str> {
    if exists && !owned {
        return Err("foreign unit");
    }
    let mut actions = Vec::new();
    if disable {
        actions.push(Action::Disable);
    }
    // Python rechecks existence after an optional disable, preserving the prior effect order.
    actions.push(Action::UnlinkUnit);
    actions.push(Action::DaemonReload);
    Ok(actions)
}

/// The dry-run prints only systemctl actions, in the same order as execution.
pub fn dry_run_operations(install: bool, optional: bool) -> Vec<Operation> {
    if install {
        let mut result = vec![Operation::DaemonReload];
        if optional {
            result.push(Operation::Enable);
        }
        result
    } else {
        let mut result = Vec::new();
        if optional {
            result.push(Operation::Disable);
        }
        result.push(Operation::DaemonReload);
        result
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    #[test]
    fn argv_and_operation_allowlist() {
        for (name, tail) in [
            ("daemon-reload", vec!["daemon-reload"]),
            ("enable", vec!["enable", UNIT_NAME]),
            ("disable", vec!["disable", UNIT_NAME]),
        ] {
            let operation = Operation::parse(name).unwrap();
            let argv = systemctl_argv("/usr/bin/systemctl", operation);
            assert_eq!(
                &argv[..3],
                ["/usr/bin/systemctl", "--user", "--no-ask-password"]
            );
            assert_eq!(&argv[3..], tail);
        }
        assert!(Operation::parse("start").is_none());
    }
    #[test]
    fn executable_lexical_policy() {
        assert_eq!(
            render_executable("relative"),
            Err(ExecutableError::NotAbsolute)
        );
        assert_eq!(
            render_executable("/bad\npath"),
            Err(ExecutableError::ControlCharacter)
        );
        for (character, error) in [
            ('"', ExecutableError::DoubleQuote),
            ('\'', ExecutableError::SingleQuote),
            ('\\', ExecutableError::Backslash),
            ('$', ExecutableError::DollarSign),
            ('*', ExecutableError::Asterisk),
            ('?', ExecutableError::QuestionMark),
            ('[', ExecutableError::OpeningSquareBracket),
        ] {
            assert_eq!(
                render_executable(&format!("/bad{character}path")),
                Err(error)
            );
        }
        assert_eq!(
            render_executable("/ü/100%/python"),
            Ok("\"/ü/100%%/python\"".into())
        );
    }
    #[test]
    fn executable_error_messages_preserve_path_compatibility() {
        for (path, expected) in [
            (
                "/home/a\"b/python",
                "daemon Python executable contains unsupported double quote: /home/a\"b/python",
            ),
            (
                "/home/a'b/python",
                "daemon Python executable contains unsupported single quote: /home/a'b/python",
            ),
            (
                "/home/a\\b/python",
                "daemon Python executable contains unsupported backslash: /home/a\\b/python",
            ),
            (
                "/home/$name/bin/python",
                "daemon Python executable contains unsupported dollar sign: /home/$name/bin/python",
            ),
            (
                "/home/a*b/python",
                "daemon Python executable contains unsupported asterisk: /home/a*b/python",
            ),
            (
                "/home/a?b/python",
                "daemon Python executable contains unsupported question mark: /home/a?b/python",
            ),
            (
                "/home/a[b/python",
                "daemon Python executable contains unsupported opening square bracket: /home/a[b/python",
            ),
            (
                "venv/bin/python",
                "daemon Python executable must be absolute",
            ),
            (
                "/bad\npath",
                "daemon Python executable contains a control character",
            ),
        ] {
            let error = render_executable(path).unwrap_err();
            assert_eq!(error.format_message(path), expected);
        }
    }
    #[test]
    fn golden_unit() {
        let expected = "# X-AirPods-HR-Linux-Managed: 1\n# Generated by airpods-hubd-service. Local edits may be replaced.\n[Unit]\nDescription=AirPods persistent local sensor daemon\n\n[Service]\nType=simple\nExecStart=\"/opt/airpods/bin/python\" -m airpods_hr._hubd.main\nRestart=no\nKillSignal=SIGTERM\nSuccessExitStatus=130 143\nTimeoutStopSec=330\nUMask=0077\nNoNewPrivileges=yes\n\n[Install]\nWantedBy=default.target\n";
        assert_eq!(render_unit("/opt/airpods/bin/python"), Ok(expected.into()));
    }
    #[test]
    fn ownership_exec_and_install_truth_table() {
        assert!(is_project_owned(&format!("{OWNERSHIP_MARKER}\n")));
        assert!(!is_project_owned(&format!(" {OWNERSHIP_MARKER}\n")));
        assert_eq!(installed_exec_start(""), None);
        assert_eq!(installed_exec_start("ExecStart=x\n"), Some("x"));
        assert_eq!(installed_exec_start("ExecStart=x\nExecStart=y\n"), None);
        let absent = installation_state(None, "x");
        assert!(!absent.owned && !absent.exec_start_matches);
        let owned = installation_state(Some(&format!("{OWNERSHIP_MARKER}\nExecStart=x\n")), "x");
        assert!(owned.owned && owned.exec_start_matches);
        for exists in [false, true] {
            for owned in [false, true] {
                for matches in [false, true] {
                    assert_eq!(
                        installation_valid(exists, owned, matches),
                        exists && owned && matches
                    );
                }
            }
        }
        for exists in [false, true] {
            for owned in [false, true] {
                for force in [false, true] {
                    for optional in [false, true] {
                        assert_eq!(
                            install_plan(exists, owned, force, optional).is_ok(),
                            !exists || owned || force
                        );
                        assert_eq!(
                            uninstall_plan(exists, owned, optional).is_ok(),
                            !exists || owned
                        );
                    }
                }
            }
        }
        assert_eq!(
            dry_run_operations(true, true),
            vec![Operation::DaemonReload, Operation::Enable]
        );
        assert_eq!(
            dry_run_operations(false, true),
            vec![Operation::Disable, Operation::DaemonReload]
        );
    }
}

#[cfg(test)]
mod appimage_tests {
    use super::*;
    #[test]
    fn fixed_appimage_command_preserves_python_unit_and_quotes_percent_and_spaces() {
        let path = "/home/example/Air Pods/100%/app.AppImage";
        assert_eq!(
            appimage_exec_start(path).unwrap(),
            "\"/home/example/Air Pods/100%%/app.AppImage\" --internal-daemon-service"
        );
        let old = render_unit(path).unwrap();
        let packaged = render_appimage_unit(path).unwrap();
        assert_eq!(
            packaged,
            old.replace(
                &exec_start(path).unwrap(),
                &appimage_exec_start(path).unwrap()
            )
            .replace("NoNewPrivileges=yes", "NoNewPrivileges=no\nKillMode=mixed")
        );
        assert!(!packaged.contains("/bin/sh"));
        assert_eq!(
            installed_exec_start(&packaged).unwrap(),
            appimage_exec_start(path).unwrap()
        );
    }
    #[test]
    fn privilege_words_inside_a_path_are_preserved_as_path_text() {
        let path = "/data/NoNewPrivileges=yes/app.AppImage";
        let unit = render_appimage_unit(path).unwrap();
        assert_eq!(
            installed_exec_start(&unit).unwrap(),
            appimage_exec_start(path).unwrap()
        );
        assert!(unit.contains("\nNoNewPrivileges=no\nKillMode=mixed\n"));
    }
    #[test]
    fn appimage_paths_fail_closed_using_existing_python_path_policy() {
        for path in [
            "relative", "/a\nb", "/a$b", "/a\"b", "/a'b", "/a*b", "/a?b", "/a[b", "/a\\b",
        ] {
            assert!(render_appimage_unit(path).is_err());
            assert_eq!(
                render_appimage_unit(path).unwrap_err(),
                render_unit(path).unwrap_err()
            );
        }
    }
}
